title: We dig, dig, dig, dig
author: JohnSp
email: John@houseofspear.com
description: > # this means to ignore newlines until "baseurl:"
  Blog test
# social links
twitter_username: @jspear
github_username:  SpearJohn

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
